#!/usr/bin/env python3
"""Writes the demo build's canned server replies as a C header.

    python3 tools/make_demo.py <out.h>

From tests/data: replies saved from the live server, the same ones the
desktop test parses. Holdem.c's HOLDEM_DEMO build serves them in place of
FujiNet: the table list, and a table state picked by the table name
("turn", "show", or anything else for the flop).
"""
import os
import sys

DATA = os.path.join(os.path.dirname(__file__), "..", "tests", "data")
REPLIES = [
    ("demoTables", "holdem_tables.bin"),
    ("demoFlop", "holdem_state_flop.bin"),
    ("demoTurn", "holdem_state_turn.bin"),
    ("demoShowdown", "holdem_state_showdown.bin"),
]


def main(out):
    lines = ["/* Generated by tools/make_demo.py from tests/data; do not edit. */"]
    for name, path in REPLIES:
        data = open(os.path.join(DATA, path), "rb").read()
        lines.append("static const UInt8 %s[%d] = {" % (name, len(data)))
        for i in range(0, len(data), 12):
            lines.append("    " + ", ".join("0x%02X" % b for b in data[i:i + 12]) + ",")
        lines.append("};")
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main(sys.argv[1])
