/* GENERATED by src/nes/mkchr.py from src/coleco/font.bin and udg.h.
 * Tile numbers in the CHARS1 pattern table, and the glyph codes the
 * shadow screen is kept in. 233 of 256 tiles used. Do not edit. */
#ifndef TILES_H
#define TILES_H

#define UDG_CARD_TL            0x80
#define UDG_CARD_BL            0x81
#define UDG_CARD_TOP           0x82
#define UDG_CARD_BOT           0x83
#define UDG_CARD_TOP_TRIM      0x84
#define UDG_CARD_BOT_TRIM      0x85
#define UDG_CARD_VERT          0x86
#define UDG_CARD_BR_STUB       0x96
#define UDG_CARD_TR_STUB       0x97
#define UDG_BACK_RCOL_TOP      0x9B
#define UDG_BACK_RCOL_MID      0x9C
#define UDG_BACK_RCOL_BOT      0x9D
#define UDG_BACK_L_TOP         0x9E
#define UDG_BACK_R_TOP         0x9F
#define UDG_BACK_L_MID         0xA0
#define UDG_BACK_R_MID         0xA1
#define UDG_BACK_L_BOT         0xA2
#define UDG_BACK_R_BOT         0xA3
#define UDG_BOX_TL             0xA4
#define UDG_BOX_TR             0xA5
#define UDG_BOX_H              0xA6
#define UDG_BOX_BL             0xA7
#define UDG_BOX_BR             0xA8
#define UDG_BOX_V              0xA9
#define UDG_RANK_2             0xAA
#define UDG_RANK_3             0xAB
#define UDG_RANK_4             0xAC
#define UDG_RANK_5             0xAD
#define UDG_RANK_6             0xAE
#define UDG_RANK_7             0xAF
#define UDG_RANK_8             0xB0
#define UDG_RANK_9             0xB1
#define UDG_RANK_T             0xB2
#define UDG_RANK_J             0xB3
#define UDG_RANK_Q             0xB4
#define UDG_RANK_K             0xB5
#define UDG_RANK_A             0xB6
#define UDG_SUIT_SPADE         0xB7
#define UDG_SUIT_CLUB          0xB8
#define UDG_SUIT_DIAMOND       0xB9
#define UDG_SUIT_HEART         0xBA
#define UDG_CHIP               0xBC
#define UDG_HIDDEN_L           0xBF
#define UDG_HIDDEN_R           0xC0
#define UDG_SCREEN_TL          0xC1
#define UDG_SCREEN_TR          0xC2
#define UDG_SCREEN_BL          0xC3
#define UDG_SCREEN_BR          0xC4

#define T_UL_CHARS " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"

#define T_TEXT                 0x00  /* ASCII 0x20-0x5F, white on felt */
#define T_STATUS               0x40  /* ASCII 0x20-0x5F, white on black */
#define T_CARD_TL_RG           0x80
#define T_CARD_BL_RG           0x81
#define T_CARD_TOP_RG          0x82
#define T_CARD_BOT_RG          0x83
#define T_CARD_TOP_TRIM_RG     0x84
#define T_CARD_BOT_TRIM_RG     0x85
#define T_CARD_VERT_RG         0x86
#define T_CARD_BR_STUB_RG      0x87
#define T_CARD_TR_STUB_RG      0x88
#define T_BOX_TL_RG            0x89
#define T_BOX_TR_RG            0x8A
#define T_BOX_H_RG             0x8B
#define T_BOX_BL_RG            0x8C
#define T_BOX_BR_RG            0x8D
#define T_BOX_V_RG             0x8E
#define T_CHIP_RG              0x8F
#define T_CARD_VERT_RW         0x90
#define T_BACK_RCOL_TOP_RW     0x91
#define T_BACK_RCOL_MID_RW     0x92
#define T_BACK_RCOL_BOT_RW     0x93
#define T_BACK_L_TOP_RW        0x94
#define T_BACK_R_TOP_RW        0x95
#define T_BACK_L_MID_RW        0x96
#define T_BACK_R_MID_RW        0x97
#define T_BACK_L_BOT_RW        0x98
#define T_BACK_R_BOT_RW        0x99
#define T_HIDDEN_L_RW          0x9A
#define T_HIDDEN_R_RW          0x9B
#define T_BLANK_W              0x9C  /* card face interior */
#define T_RANK_RW              0x9D  /* 13 ranks 2..A, red on white */
#define T_RANK_KW              0xAA  /* 13 ranks 2..A, black on white */
#define T_SUIT_DIAMOND_RW      0xB7
#define T_SUIT_HEART_RW        0xB8
#define T_SUIT_SPADE_KW        0xB9
#define T_SUIT_CLUB_KW         0xBA
#define T_SCREEN_TL_GK         0xBB
#define T_SCREEN_TR_GK         0xBC
#define T_SCREEN_BL_GK         0xBD
#define T_SCREEN_BR_GK         0xBE
#define T_STATUS_UL            0xBF  /* T_UL_CHARS order, red underline */
#define T_TOPBAR_SPACE         0xE4
#define T_TOPBAR_CARD_TL       0xE5
#define T_TOPBAR_CARD_TOP      0xE6
#define T_TOPBAR_CARD_TR_STUB  0xE7
#define T_TOPBAR_CARD_TOP_TRIM 0xE8

#endif /* TILES_H */
